### ISSUE TITLE
Partial Application of mappers

### ISSUE THREAD

**Issue by erlandsona** [orus-io/elm-spa#4]
Just looking at the README, seems redundant to apply the same `mappers` function to each invocation of `addProtectedPage`, `addPublicPage`. 
Can it not be added to the configuration object?
I'd argue the same could be said for the `match` functions... Those could just all be one big `Route.toPage : Url -> Page` function passed to the config. 
```elm
type Page
    = NotFound
    | Page1
    | Page2
    
toPage : Url -> Page
toPage url =
    case url.path of
        ["stuff"] ->
            Page1
          
        ["things"] ->
            Page2
          
        _ ->
            NotFound 
```
Or if the `Maybe` is used as a means of building the `NotFound` use case into the framework
```elm
type Page
    = Page1
    | Page2 { id : Maybe Int }

toPage : Url -> Maybe Page
toPage url =
    case url.path of
        ["stuff"] ->
            Just Page1

        ["things"] ->
            Just (Page2 (parseId url.query))

        _ -> 
            Nothing
```

**Comment by cdevienne** [comment]
Hi @erlandsona, sorry I did not respond earlier

We cannot add the mappers in the configuration object because each call to 'addXXPage' will specialize the function differently (ie, from a layer to the next one).

If you have a global 'toPage' function, you would still need to pass something the 'addXXPage' to associate a 'Page' type to a page definition. Unless each page definition has an embedded comparator to do the job, which would forbid having a same page for different routes.

I would be happy to be proven wrong of course, don't hesitate to make a PR if you can implement your ideas!

Thanks for you interest in this project
